/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sorenon_physicality_physv2_PhysJNI */

#ifndef _Included_net_sorenon_physicality_physv2_PhysJNI
#define _Included_net_sorenon_physicality_physv2_PhysJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sorenon_physicality_physv2_PhysJNI
 * Method:    createPhysicsWorld
 * Signature: (Lnet/minecraft/world/level/Level;Lnet/sorenon/physicality/physv2/PhysicsCallback;)I
 */
JNIEXPORT jint JNICALL Java_net_sorenon_physicality_physv2_PhysJNI_createPhysicsWorld
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     net_sorenon_physicality_physv2_PhysJNI
 * Method:    step
 * Signature: (IF)I
 */
JNIEXPORT jint JNICALL Java_net_sorenon_physicality_physv2_PhysJNI_step
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_sorenon_physicality_physv2_PhysJNI
 * Method:    addPhysicsBody
 * Signature: (IFFFJ)I
 */
JNIEXPORT jint JNICALL Java_net_sorenon_physicality_physv2_PhysJNI_addPhysicsBody
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     net_sorenon_physicality_physv2_PhysJNI
 * Method:    getBodyPosition
 * Signature: (IJLorg/joml/Vector3f;)I
 */
JNIEXPORT jint JNICALL Java_net_sorenon_physicality_physv2_PhysJNI_getBodyPosition
  (JNIEnv *, jclass, jint, jlong, jobject);

/*
 * Class:     net_sorenon_physicality_physv2_PhysJNI
 * Method:    getBodyRenderTransform
 * Signature: (IJLorg/joml/Vector3f;Lorg/joml/Quaternionf;)I
 */
JNIEXPORT jint JNICALL Java_net_sorenon_physicality_physv2_PhysJNI_getBodyRenderTransform
  (JNIEnv *, jclass, jint, jlong, jobject, jobject);

/*
 * Class:     net_sorenon_physicality_physv2_PhysJNI
 * Method:    blockUpdated
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_net_sorenon_physicality_physv2_PhysJNI_blockUpdated
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
